name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 12
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        key: ${{secrets.SSH_KEY}}
        port: 22
        script: whoami