name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  job-one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 12
      uses: appleboy/ssh-action@master
      with: 
        host: 150.230.21.45
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd Yemma-Lehnina
          git pull
          cd frontend_yemmalehnina
          npm install
          npm run build
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
          cd ../backend_yemmalehnina
          sudo lsof -i -P -n |grep java| head -1 | echo $(awk '{print $2}')          
